---
title: "QC_GSE181279"
author: "Jihun Gu"
output: html_document
---

```{r}
library(dplyr)
library(ggplot2)
library("ggpubr")
install.packages('Seurat')
library(Seurat)
```

```{r, warning=FALSE}
pbmc.data <- Read10X(data.dir = "data/")
pbmc <- CreateSeuratObject(counts = pbmc.data, project = "pbmc3k", min.cells = 3, min.features = 200)
pbmc
```
```{r}
# The [[ operator can add columns to object metadata. This is a great place to stash QC stats
pbmc[["percent.mt"]] <- PercentageFeatureSet(pbmc, pattern = "^MT-")

# Visualize QC metrics as a violin plot
VlnPlot(pbmc, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
```

```{r}
percent_mt <- pbmc@meta.data$percent.mt
threshold <- quantile(percent_mt, 0.95)
threshold
```


```{r}
# FeatureScatter is typically used to visualize feature-feature relationships, but can be used
# for anything calculated by the object, i.e. columns in object metadata, PC scores etc.
dev.new(width=10, height=5, unit="in")
plot1 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "percent.mt")
plot1 #number above plot - pearson correlation
plot2 <- FeatureScatter(pbmc, feature1 = "nCount_RNA", feature2 = "nFeature_RNA")
plot2

pbmc <- subset(pbmc, subset = nFeature_RNA > 500 & nFeature_RNA < 3000 & percent.mt < 5 & nCount_RNA < 15000) #using nCounts to filter bad quality cells 15000 - 20000 threshold

pbmc <- NormalizeData(pbmc, normalization.method = "LogNormalize", scale.factor = 10000)

pbmc <- NormalizeData(pbmc)
print(pbmc)
```


```{r}
#Identification of highly variable features
pbmc <- FindVariableFeatures(pbmc, selection.method = "vst", nfeatures = 2000)

# Identify the 10 most highly variable genes
top10 <- head(VariableFeatures(pbmc), 10)

# plot variable features with and without labels
plot1 <- VariableFeaturePlot(pbmc)
plot2 <- LabelPoints(plot = plot1, points = top10, repel = TRUE, xnudge = 0, ynudge = 0)
#CombinePlots(plots = list(plot1, plot2))
plot1
plot2
```

```{r}
#Scaling the data
all.genes <- rownames(pbmc)
pbmc <- ScaleData(pbmc, features = all.genes)

#Linear dimensional reduction
pbmc <- RunPCA(pbmc, features = VariableFeatures(object = pbmc))

#Examine and visualize PCA results a few different ways
print(pbmc[["pca"]], dims = 1:5, nfeatures = 5)
VizDimLoadings(pbmc, dims = 1:2, reduction = "pca")
DimPlot(pbmc, reduction = "pca")
```
```{r}
#Determine the dimensionality of the dataset
pbmc <- JackStraw(pbmc, num.replicate = 100)
pbmc <- ScoreJackStraw(pbmc, dims = 1:20)

JackStrawPlot(pbmc, dims = 1:15) #try to choose PC 10-12
ElbowPlot(pbmc)

#Cluster the cells
pbmc_5 <- FindNeighbors(pbmc, dims = 1:5) #was 1:5
pbmc_5 <- FindClusters(pbmc_5, resolution = 0.1) #was 0.1


# Look at cluster IDs of the first 5 cells
head(Idents(pbmc_5), 5)
```

```{r}
#Run non-linear dimensional reduction (UMAP/tSNE)
# If you haven't installed UMAP, you can do so via reticulate::py_install(packages =
# 'umap-learn')
pbmc_5 <- RunUMAP(pbmc_5, dims = 1:5)
# note that you can set `label = TRUE` or use the LabelClusters function to help label
# individual clusters
DimPlot(pbmc_5, reduction = "umap")

#pbmc_8 <- RunUMAP(pbmc_8, dims = 1:8)
# note that you can set `label = TRUE` or use the LabelClusters function to help label
# individual clusters
#DimPlot(pbmc_8, reduction = "umap") #using @meta.data for subsets; check with azimuth

saveRDS(pbmc_5, file = "pbmc_data_5.rds")
```

```{r}
#Finding differentially expressed features
# find all markers of cluster 1
cluster1.markers <- FindMarkers(pbmc_5, ident.1 = 1, min.pct = 0.25)
head(cluster1.markers, n = 5)

cluster2.markers <- FindMarkers(pbmc_5, ident.1 = 2, min.pct = 0.25)
head(cluster2.markers, n = 5)

# find all markers distinguishing cluster 1 from cluster 2 
cluster1_2.markers <- FindMarkers(pbmc_5, ident.1 = 1, ident.2 = c(2), min.pct = 0.25)
head(cluster1_2.markers, n = 5)
```

```{r}
# find markers for every cluster compared to all remaining cells, report only the positive ones

pbmc.markers <- FindAllMarkers(pbmc_5, only.pos = TRUE, min.pct = 0.25, logfc.threshold = 0.25)
print(pbmc.markers %>% group_by(cluster) %>% top_n(n = 2, wt = avg_log2FC), n = 28)


#plotting raw counts as well
VlnPlot(pbmc_5, features = c("CD14", "LYZ", "GNLY"), slot = "counts", log = TRUE)

#cluster 0 - NK, cluster 4 - CD14+ Mono; cluster 2 - CD4+ T; cluster 3 - B; cluster 1 - CD8+ T

VlnPlot(pbmc_5, features = c("MS4A1", "GNLY", "CD14", "CD8A", "FCGR3A", "LYZ", 
                               "NKG7"))

top10 <- pbmc.markers %>% group_by(cluster) %>% top_n(n = 10, wt = avg_log2FC)
DoHeatmap(pbmc_5, features = top10$gene) + NoLegend()
```

```{r}
new.cluster.ids <- c("NK", "CD8+", "CD4+", "B", "CD14+ Mono")
names(new.cluster.ids) <- levels(pbmc_5)
pbmc_5 <- RenameIdents(pbmc_5, new.cluster.ids)
DimPlot(pbmc_5, reduction = "umap", label = FALSE, pt.size = 0.5) #check number of cells per cluster
table(Idents(pbmc_5))
```
